# Generated by Django 4.1 on 2022-09-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('wrong_answer1', models.CharField(max_length=100)),
                ('wrong_answer2', models.CharField(max_length=100)),
                ('wrong_answer3', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
