# Generated by Django 4.1 on 2022-09-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
